import { Model } from './types';

export const MOCK_MODELS: Model[] = [
  {
    id: '1',
    name: 'Red Bull Racing RB20 - Max Verstappen - Winner Bahrain GP 2024',
    manufacturer: 'Spark',
    year: 2024,
    driver: 'Max Verstappen',
    team: 'Red Bull Racing',
    price: '€84.95',
    scale: '1:43',
  },
  {
    id: '2',
    name: 'Ferrari SF-24 - Charles Leclerc - Monaco GP 2024',
    manufacturer: 'Looksmart',
    year: 2024,
    driver: 'Charles Leclerc',
    team: 'Ferrari',
    price: '€129.00',
    scale: '1:43',
  },
  {
    id: '3',
    name: 'Mercedes W15 - Lewis Hamilton - British GP 2024',
    manufacturer: 'Minichamps',
    year: 2024,
    driver: 'Lewis Hamilton',
    team: 'Mercedes-AMG Petronas',
    price: '€89.95',
    scale: '1:43',
  },
  {
    id: '4',
    name: 'McLaren MCL38 - Lando Norris - Miami GP Winner 2024',
    manufacturer: 'Spark',
    year: 2024,
    driver: 'Lando Norris',
    team: 'McLaren',
    price: '€94.95',
    scale: '1:43',
  },
  {
    id: '5',
    name: 'Aston Martin AMR24 - Fernando Alonso - Testing 2024',
    manufacturer: 'Spark',
    year: 2024,
    driver: 'Fernando Alonso',
    team: 'Aston Martin',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '6',
    name: 'McLaren MP4/4 - Ayrton Senna - Winner Monaco GP 1988',
    manufacturer: 'Minichamps',
    year: 1988,
    driver: 'Ayrton Senna',
    team: 'McLaren',
    price: '€89.95',
    scale: '1:43',
  },
  {
    id: '7',
    name: 'Ferrari F2004 - Michael Schumacher - World Champion 2004',
    manufacturer: 'BBR',
    year: 2004,
    driver: 'Michael Schumacher',
    team: 'Ferrari',
    price: '€449.00',
    scale: '1:18',
  },
  {
    id: '8',
    name: 'Mercedes W11 - Lewis Hamilton - Turkish GP Winner 2020',
    manufacturer: 'Spark',
    year: 2020,
    driver: 'Lewis Hamilton',
    team: 'Mercedes-AMG Petronas',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '9',
    name: 'Red Bull RB18 - Sergio Perez - Monaco GP 2022',
    manufacturer: 'Spark',
    year: 2022,
    driver: 'Sergio Perez',
    team: 'Red Bull Racing',
    price: '€84.95',
    scale: '1:43',
  },
  {
    id: '10',
    name: 'Williams FW14B - Nigel Mansell - World Champion 1992',
    manufacturer: 'Minichamps',
    year: 1992,
    driver: 'Nigel Mansell',
    team: 'Williams',
    price: '€94.50',
    scale: '1:43',
  },
  {
    id: '11',
    name: 'Ferrari SF-23 - Carlos Sainz - Singapore GP Winner 2023',
    manufacturer: 'Looksmart',
    year: 2023,
    driver: 'Carlos Sainz',
    team: 'Ferrari',
    price: '€119.00',
    scale: '1:43',
  },
  {
    id: '12',
    name: 'Alpine A522 - Fernando Alonso - Hungarian GP 2022',
    manufacturer: 'Spark',
    year: 2022,
    driver: 'Fernando Alonso',
    team: 'Alpine',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '13',
    name: 'Benetton B194 - Michael Schumacher - Monaco GP 1994',
    manufacturer: 'Minichamps',
    year: 1994,
    driver: 'Michael Schumacher',
    team: 'Benetton',
    price: '€89.95',
    scale: '1:43',
  },
  {
    id: '14',
    name: 'Red Bull RB19 - Max Verstappen - Japan GP 2023',
    manufacturer: 'Spark',
    year: 2023,
    driver: 'Max Verstappen',
    team: 'Red Bull Racing',
    price: '€84.95',
    scale: '1:43',
  },
  {
    id: '15',
    name: 'Mercedes W13 - George Russell - Brazil GP 2022',
    manufacturer: 'Minichamps',
    year: 2022,
    driver: 'George Russell',
    team: 'Mercedes-AMG Petronas',
    price: '€89.95',
    scale: '1:43',
  },
  {
    id: '16',
    name: 'McLaren MCL60 - Oscar Piastri - Qatar Sprint Winner 2023',
    manufacturer: 'Spark',
    year: 2023,
    driver: 'Oscar Piastri',
    team: 'McLaren',
    price: '€84.95',
    scale: '1:43',
  },
  {
    id: '17',
    name: 'Aston Martin AMR23 - Lance Stroll - Monaco GP 2023',
    manufacturer: 'Spark',
    year: 2023,
    driver: 'Lance Stroll',
    team: 'Aston Martin',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '18',
    name: 'Haas VF-23 - Nico Hulkenberg - Testing 2023',
    manufacturer: 'Spark',
    year: 2023,
    driver: 'Nico Hulkenberg',
    team: 'Haas',
    price: '€74.95',
    scale: '1:43',
  },
  {
    id: '19',
    name: 'Ferrari F1-75 - Charles Leclerc - Bahrain GP Winner 2022',
    manufacturer: 'BBR',
    year: 2022,
    driver: 'Charles Leclerc',
    team: 'Ferrari',
    price: '€399.00',
    scale: '1:18',
  },
  {
    id: '20',
    name: 'Williams FW44 - Alex Albon - Australian GP 2022',
    manufacturer: 'Spark',
    year: 2022,
    driver: 'Alex Albon',
    team: 'Williams',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '21',
    name: 'Lotus 72 - Emerson Fittipaldi - British GP Winner 1972',
    manufacturer: 'Spark',
    year: 1972,
    driver: 'Emerson Fittipaldi',
    team: 'Lotus',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '22',
    name: 'Red Bull RB16B - Sergio Perez - Azerbaijan GP Winner 2021',
    manufacturer: 'Minichamps',
    year: 2021,
    driver: 'Sergio Perez',
    team: 'Red Bull Racing',
    price: '€94.95',
    scale: '1:43',
  },
  {
    id: '23',
    name: 'Mercedes W12 - Valtteri Bottas - Turkish GP 2021',
    manufacturer: 'Spark',
    year: 2021,
    driver: 'Valtteri Bottas',
    team: 'Mercedes-AMG Petronas',
    price: '€79.90',
    scale: '1:43',
  },
  {
    id: '24',
    name: 'McLaren MCL35M - Daniel Ricciardo - Monza GP Winner 2021',
    manufacturer: 'Spark',
    year: 2021,
    driver: 'Daniel Ricciardo',
    team: 'McLaren',
    price: '€89.95',
    scale: '1:43',
  },
];
